name : CI - Continuous Integration

on:
  pull_request:
    branches:
      - main

#------------ JOBS what I will do with this CI ---------

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    