name: CD — Continuous Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: production

    outputs:
      image-tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test CD runner
        run: |
          echo "CD workflow started"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{env.AWS_REGION}}
          role-session-name: GitHubActions-ShipKit-${{ github.run_id }}
      - name: Test AWS connection 
        run: aws sts get-caller-identity